# Generated by Django 5.0.7 on 2024-07-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('capacity', models.IntegerField()),
                ('type', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Tickit_app.venue')),
            ],
        ),
    ]
